Repository zino-hofmann/graphql-flutter, pull requests merged in 2018-09, with the labels that each got.

#79 Document parser
  lib/src/core/query_manager.dart
  lib/src/utilities/get_from_ast.dart
  pubspec.yaml
Labels: enhancement

#81 Improve context
  lib/src/core/query_manager.dart
  lib/src/core/query_options.dart
  lib/src/link/http/link_http.dart
  lib/src/widgets/mutation.dart
  lib/src/widgets/query.dart
Labels: enhancement

#80 Only create a new observable query if options have changed
  lib/src/core/query_options.dart
  lib/src/widgets/mutation.dart
  lib/src/widgets/query.dart
Labels: bug

#82 Enforce strong typing and linting
  analysis_options.yaml
  lib/src/cache/in_memory.dart
  lib/src/core/graphql_error.dart
  lib/src/core/query_manager.dart
  lib/src/core/query_options.dart
  lib/src/graphql_client.dart
  lib/src/link/http/fallback_http_config.dart
  lib/src/link/http/http_config.dart
  lib/src/link/http/link_http.dart
  lib/src/link/operation.dart
  lib/src/socket_client.dart
  lib/src/utilities/promise.dart
  lib/src/websocket/messages.dart
  lib/src/websocket/socket.dart
  lib/src/widgets/graphql_consumer.dart
  lib/src/widgets/graphql_provider.dart
  lib/src/widgets/mutation.dart
  lib/src/widgets/query.dart
  lib/src/widgets/subscription.dart
Labels: enhancement, next

#84 Patch 10
  README.md
  lib/src/widgets/mutation.dart
Labels: bug

#88 Patch 11
  example/lib/main.dart
  lib/src/link/http/link_http.dart
Labels: bug, next

#89 Implement the onComplete callback for the Mutation widget
  example/lib/main.dart
  lib/src/widgets/mutation.dart
  lib/src/widgets/query.dart
Labels: bug, enhancement, next

#90 Added optional parameter initPayload
  lib/src/socket_client.dart
  lib/src/websocket/messages.dart
Labels: enhancement, next

#92 🔧 Fixed a bug where getQueryResult was called before client cloud init
  lib/src/widgets/query.dart
Labels: bug

#96 Patch 13
  lib/src/core/graphql_error.dart
  lib/src/core/observable_query.dart
  lib/src/core/query_manager.dart
  lib/src/core/query_options.dart
  lib/src/core/query_result.dart
  lib/src/link/fetch_result.dart
  lib/src/scheduler/scheduler.dart
  lib/src/utilities/get_from_ast.dart
  lib/src/widgets/mutation.dart
  lib/src/widgets/query.dart
Labels: bug, next

#98 Propagate GraphQL errors to caller instead of throwing network exception
  lib/src/core/query_manager.dart
Labels: bug

#100 Examples
  example/lib/main.dart
  lib/src/core/graphql_request.dart
  lib/src/core/query_manager.dart
  lib/src/graphql_client.dart
  lib/src/link/operation.dart
  lib/src/widgets/mutation.dart
  lib/src/widgets/query.dart
Labels: bug, next

#107 🔧 Fix connectivity errors not being thown on and streamed
  example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  lib/src/core/graphql_error.dart
  lib/src/core/query_manager.dart
  lib/src/core/query_result.dart
Labels: bug, enhancement
