Repository zino-hofmann/graphql-flutter, pull requests merged in 2021-11, with the labels that each got.

#952 docs(graphql_flutter): fix typo
  packages/graphql_flutter/README.md
Labels: :bookmark_tabs: docs

#978 Dependeces migration and test disabling (for now)
  packages/graphql/pubspec.yaml
  packages/graphql/test/coverage.dart
  packages/graphql/test/websocket_test.dart
  packages/graphql_flutter/example/android/app/src/main/AndroidManifest.xml
  packages/graphql_flutter/example/android/app/src/main/java/com/example/app/MainActivity.java
  packages/graphql_flutter/pubspec.yaml
Labels: :beginner: ci/cd, :syringe: dependences

#985 ci: try to upgrade the node version to make the package release
  .circleci/config.yml
  .codecov.yml
Labels: :beginner: ci/cd

#982 Fixed typo in the README.md
  packages/graphql/README.md
Labels: :bookmark_tabs: docs

#932 perf: open Hive boxes concurrently
  packages/graphql_flutter/lib/src/hive_init.dart
Labels: :bookmark_tabs: docs
