Repository zino-hofmann/graphql-flutter, pull requests merged in 2022-04, with the labels that each got.

#1089 ci: fixed yaml format
  .github/workflows/graphql_flutter_tests.yml
Labels: :beginner: ci/cd

#1086 ci: split the release process between package
  .circleci/config.yml
  .github/workflows/graphql_flutter_release.yml
  .github/workflows/graphql_release.yml
  packages/graphql/CHANGELOG.md
  packages/graphql/pubspec.yaml
  packages/graphql_flutter/CHANGELOG.md
  packages/graphql_flutter/pubspec.yaml
Labels: enhancement, :beginner: ci/cd

#1088 docs: update contributors and maintainers guide lines
  CONTRIBUTING.md
  docs/dev/MAINTAINERS.md
Labels: :bookmark_tabs: docs

#1096 packages: prepare graphql v5.1.0
  .github/workflows/graphql_flutter_release.yml
  .github/workflows/graphql_release.yml
  .github/workflows/packages_release.yml
  Makefile
  docs/dev/MAINTAINERS.md
  packages/graphql/.pubignore
  packages/graphql/CHANGELOG.md
  packages/graphql/changelog.json
  packages/graphql/pubspec.yaml
  packages/graphql_flutter/.pubignore
  packages/graphql_flutter/changelog.json
Labels: released

#1098 packages: prepare graphql_flutter v5.1.0
  .github/workflows/packages_release.yml
  packages/graphql_flutter/CHANGELOG.md
  packages/graphql_flutter/pubspec.yaml
Labels: released

#1099 feat(graphql): Tighten the OnMutationCompleted function
  packages/graphql/lib/src/core/mutation_options.dart
Labels: dart type

#1103 ci: stop running release during the outside PRs
  .github/workflows/graphql_flutter_release.yml
  .github/workflows/graphql_release.yml
Labels: :beginner: ci/cd

#1108 feat(graphql_flutter): Decouple GraphQLClient Provider
  packages/graphql_flutter/lib/src/widgets/hooks/mutation.dart
  packages/graphql_flutter/lib/src/widgets/hooks/query.dart
  packages/graphql_flutter/lib/src/widgets/hooks/subscription.dart
  packages/graphql_flutter/lib/src/widgets/hooks/watch_query.dart
  packages/graphql_flutter/lib/src/widgets/mutation.dart
  packages/graphql_flutter/lib/src/widgets/query.dart
  packages/graphql_flutter/lib/src/widgets/subscription.dart
Labels: flutter, Priority: High

#1097 feat: query onError & onComplete callbacks
  melos.yaml
  packages/graphql/lib/src/core/observable_query.dart
  packages/graphql/lib/src/core/query_options.dart
  packages/graphql_flutter/lib/src/widgets/hooks/query.dart
  packages/graphql_flutter/test/widgets/query_test.dart
Labels: enhancement, Priority: High

#1116 prepare graphql_flutter beta 2
  packages/graphql_flutter/CHANGELOG.md
  packages/graphql_flutter/changelog.json
  packages/graphql_flutter/pubspec.yaml
Labels: released on @beta
