Repository zino-hofmann/graphql-flutter, pull requests merged in 2022-01, with the labels that each got.

#1003 update README.md
  packages/graphql_flutter/README.md
Labels: :bullettrain_side: doc & examples

#1005 feat: Update normalize
  packages/graphql/README.md
  packages/graphql/pubspec.yaml
Labels: enhancement, :bookmark_tabs: docs

#1006 graphql: removing print url into the console and API improvement
  packages/graphql/lib/src/links/websocket_link/websocket_client.dart
Labels: :bug: bug, dart client

#1010 graphql: restore ws test by introducing a ws echo server written in dart
  .codecov.yml
  .github/workflows/graphql_codcoverage.yml
  .github/workflows/graphql_flutter_codcoverage.yml
  packages/graphql/pubspec.yaml
  packages/graphql/test/coverage.dart
  packages/graphql/test/mock_server/ws_echo_server.dart
  packages/graphql/test/websocket_test.dart
Labels: :beginner: ci/cd, :hammer: tests, :zap: websocket

#1012 Fix close websocket on web and a few related cleanups
  .github/workflows/graphql_codcoverage.yml
  .github/workflows/graphql_flutter_codcoverage.yml
  README.md
  packages/graphql/lib/src/links/websocket_link/websocket_client.dart
  packages/graphql/test/mock_server/ws_echo_server.dart
  packages/graphql/test/websocket_test.dart
Labels: :bug: bug, dart client

#1013 feat: Add parser support
  packages/graphql/lib/src/core/_base_options.dart
  packages/graphql/lib/src/core/fetch_more.dart
  packages/graphql/lib/src/core/mutation_options.dart
  packages/graphql/lib/src/core/observable_query.dart
  packages/graphql/lib/src/core/query_manager.dart
  packages/graphql/lib/src/core/query_options.dart
  packages/graphql/lib/src/core/query_result.dart
  packages/graphql/lib/src/core/result_parser.dart
  packages/graphql/lib/src/graphql_client.dart
  packages/graphql/test/graphql_client_test.dart
  packages/graphql/test/websocket_test.dart
  packages/graphql_flutter/lib/src/widgets/mutation.dart
  packages/graphql_flutter/lib/src/widgets/query.dart
  packages/graphql_flutter/lib/src/widgets/subscription.dart
Labels: enhancement

#1021 packages: improve the pub.dev scoring
  packages/graphql/README.md
  packages/graphql_flutter/README.md
  packages/graphql_flutter/pubspec.yaml
Labels: :bullettrain_side: doc & examples
