Repository zino-hofmann/graphql-flutter, pull requests merged in 2022-02, with the labels that each got.

#1016 graphql: reworking Socket Client API to support custom header
  .github/workflows/graphql_codcoverage.yml
  .github/workflows/graphql_flutter_codcoverage.yml
  .github/workflows/release.yml
  packages/graphql/lib/src/links/gql_links.dart
  packages/graphql/lib/src/links/links.dart
  packages/graphql/lib/src/links/websocket_link/websocket_client.dart
  packages/graphql/lib/src/utilities/platform_html.dart
  packages/graphql/lib/src/utilities/platform_io.dart
  packages/graphql/test/websocket_test.dart
Labels: enhancement, dart client

#1033 Use `flutter pub add` to add dependencies
  packages/graphql/README.md
  packages/graphql_flutter/README.md
Labels: :bullettrain_side: doc & examples

#1035 ci: fixed the release process in the beta branch
  .circleci/config.yml
Labels: :beginner: ci/cd

#1041 fix: Cache-reboardcast error
  packages/graphql/lib/src/core/observable_query.dart
  packages/graphql/lib/src/core/query_manager.dart
  packages/graphql/lib/src/utilities/response.dart
Labels: :bug: bug

#1042 docs(graphql): fix typo
  packages/graphql/example/README.md
Labels: needs more info

#1050 introduces melos as workspace management and clean up of the templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/graphql_build.yml
  .github/workflows/graphql_flutter_build.yml
  Makefile
  examples/starwars/pubspec.yaml
  melos.yaml
  packages/graphql/lib/src/core/query_options.dart
Labels: enhancement

#1056 Add docs for how to update web socket headers
  packages/graphql/README.md
Labels: :bullettrain_side: doc & examples
