Repository zino-hofmann/graphql-flutter, pull requests merged in 2022-07, with the labels that each got.

#1174 ci: patch release tag to filtering the packages
  .github/workflows/packages_release.yml
Labels: :beginner: ci/cd

#1177 docs(graphql): add csrf error solution
  packages/graphql/README.md
Labels: :bookmark_tabs: docs

#1182 graphql: fixed copy and paste refactoring
  .github/workflows/graphql_build.yml
  .github/workflows/graphql_codcoverage.yml
  .github/workflows/graphql_flutter_build.yml
  .github/workflows/graphql_flutter_codcoverage.yml
  .github/workflows/graphql_flutter_tests.yml
  .github/workflows/graphql_tests.yml
  .github/workflows/packages_build.yml
  .github/workflows/packages_tests.yml
  packages/graphql/lib/src/links/websocket_link/websocket_client.dart
Labels: :bug: bug

#1160 Fix wrong default policy merging in `useWatchQuery/Mutation`.
  packages/graphql_flutter/lib/src/widgets/hooks/watch_query.dart
  packages/graphql_flutter/test/widgets/query_test.dart
Labels: :bug: bug

#1186 fix `SocketClient` to close subscription on socket close
  packages/graphql/lib/src/links/websocket_link/websocket_client.dart
  packages/graphql/test/websocket_test.dart
Labels: :bug: bug

#1185 prepare last versions beta
  .releaserc.yaml
  docs/dev/MAINTAINERS.md
  packages/graphql/CHANGELOG.md
  packages/graphql/changelog.json
  packages/graphql/pubspec.yaml
  packages/graphql_flutter/CHANGELOG.md
  packages/graphql_flutter/changelog.json
  packages/graphql_flutter/pubspec.yaml
Labels: flutter, dart client
