Repository zino-hofmann/graphql-flutter, pull requests merged in 2022-10, with the labels that each got.

#1243 ci: remove the spec dependences
  Makefile
  packages/graphql_flutter/example/lib/generated_plugin_registrant.dart
Labels: :beginner: ci/cd

#1242 Allow list of errors as payloads for graphql-transport-ws subprotocol's "error" message type
  packages/graphql/lib/src/links/websocket_link/websocket_messages.dart
  packages/graphql/test/websocket_test.dart
Labels: :bug: bug, :zap: websocket, Priority: High

#1245 prepare graphql beta release :)
  packages/graphql/CHANGELOG.md
  packages/graphql/changelog.json
  packages/graphql/pubspec.yaml
Labels: dart client

#1240 fix(graphql): deduplicate pollers
  packages/graphql/lib/src/cache/cache.dart
  packages/graphql/lib/src/scheduler/scheduler.dart
  packages/graphql/test/observable_query_test.dart
Labels: Priority: Medium
