Repository zino-hofmann/graphql-flutter, pull requests merged in 2022-03, with the labels that each got.

#1055 repository: improve the melos scripts by repository
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/packages_build.yml
  .github/workflows/packages_tests.yml
  Makefile
  melos.yaml
  packages/graphql_flutter/pubspec.yaml
Labels: :beginner: ci/cd

#1068 fix: Add .pubignore and dependency
  packages/graphql/.pubignore
  packages/graphql_flutter/.pubignore
  packages/graphql_flutter/pubspec.yaml
Labels: enhancement

#1076 Changelog Resurrection
  packages/graphql/CHANGELOG.md
  packages/graphql_flutter/CHANGELOG.md
Labels: enhancement, :beers: discussion, :beginner: ci/cd, :bookmark_tabs: docs
